name: Create Release with Branch Assets

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout and prepare main branch files
      uses: actions/checkout@v2
      with:
        ref: 'main'
      run: |
        mkdir ../xmjd6
        rsync -av --exclude='.git' --exclude='.github' ./ ../xmjd6/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'release-${{ github.run_number }}'
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload main branch files to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../xmjd6
        asset_name: xmjd6
        asset_content_type: application/octet-stream
