name: Create Release with Zipped Branch Assets and Date

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Set up environment variables
      run: |
        echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "RELEASE_TITLE=$(date +'%Y.%m.%d') 词库更新" >> $GITHUB_ENV

    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Zip main branch files excluding .git and .github
      run: zip -r xmjd6.zip . -x "*.git*" -x "*.github*"

    - name: Zip main branch pure files
      run: |
        mkdir -p Rime/
        rsync -avm --exclude='.git*' --exclude='*.github*' --exclude='squirrel*' --exclude='weasel*' --exclude='hamster*' --exclude='xmjd6.zip' . Rime/
        ls -al Rime/
        pwd

    - name: Get latest release tag and commit SHA
      id: get_tag
      uses: actions/github-script@v7
      with:
        script: |
          const release = await github.rest.repos.getLatestRelease({
            owner: 'amorphobia',
            repo: 'rabbit',
          });
          const tag = release.data.tag_name;
          const commitSha = release.data.target_commitish;
          console.log(`Latest release tag is ${tag}, commit SHA is ${commitSha}`);
          return { tag, commitSha };

    - name: Set the tag and previous commit SHA as environment variables
      run: |
        echo "RELEASE_TAG=${{ steps.get_tag.outputs.result.tag }}" >> $GITHUB_ENV
        echo "PREVIOUS_SHA=${{ steps.get_tag.outputs.result.commitSha }}" >> $GITHUB_ENV

    - name: Generate changelog
      run: |
        echo '## Changelog' > CHANGELOG.md
        git log ${{ env.PREVIOUS_SHA }}..HEAD --oneline >> CHANGELOG.md

    - name: Create Release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.CURRENT_DATE }}
        release_name: ${{ env.RELEASE_TITLE }}
        body: ${{ env.RELEASE_TITLE }}
        body_path: CHANGELOG.md  # 引用CHANGELOG.md文件内容作为release notes
        draft: false
        prerelease: false
        
    - name: Upload Rabbit-xmjd6.zip to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Rabbit-xmjd6.zip
        asset_name: Rabbit-xmjd6.zip
        asset_content_type: application/zip
        
    - name: Upload xmjd6.zip to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./xmjd6.zip
        asset_name: xmjd6.zip
        asset_content_type: application/zip
