name: Create Release with Zipped Branch Assets and Date

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
    - name: Set up environment variables
      run: |
        echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "RELEASE_TITLE=$(date +'%Y.%m.%d') 词库更新" >> $GITHUB_ENV

    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Convert .dict.yaml files to .txt
      run: |
        mkdir -p mb/xmjd6
        for dict_file in xmjd6.zidingyi.dict.yaml xmjd6.cizu.dict.yaml xmjd6.fjcy.dict.yaml xmjd6.danzi.dict.yaml xmjd6.buchong.dict.yaml xmjd6.gbk.dict.yaml xmjd6.wxw.dict.yaml
        do
          txt_file="mb/xmjd6/$(basename $dict_file .dict.yaml).txt"
          # Python script to process the .dict.yaml files
          python3 -c "
import re

def is_english(s):
    return re.match(r'^[A-Za-z0-9\s]+$', s) is not None

input_file = '$dict_file'
output_file = '$txt_file'

with open(input_file, 'r', encoding='utf-8') as file:
    lines = file.readlines()

processed_lines = []
for line in lines:
    line = line.strip()
    # Skip lines that start with #
    if line.startswith('#'):
        continue
    parts = line.split('\t')
    if len(parts) == 2:
        if is_english(parts[0]):
            processed_line = f'{parts[0]}\t{parts[1]}'
        else:
            processed_line = f'{parts[1]}\t{parts[0]}'
        processed_lines.append(processed_line)
    else:
        processed_lines.append(line)

with open(output_file, 'w', encoding='utf-8') as file:
    for processed_line in processed_lines:
        file.write(processed_line + '\\n')
          "
        done

    - name: Merge all .txt files and add header
      run: |
        header='name=星猫键道6\nkey=`abcedfghijklmnopqrstuvwxyz;\\\nlen=12\nwildcard=~\nbihua=viuoa\ncode_e2=p11+p12+p21+p22+p13+p23\ncode_e3=p11+p21+p31+p13+p23+p33\ncode_a4=p11+p21+p31+n11+p13+p23+p33+n13\n[DATA]\n'
        echo -e "$header" > mb/xmjd6/xmjd6.txt
        cat mb/xmjd6/*.txt >> mb/xmjd6/xmjd6.txt

    - name: Remove all files except xmjd6.txt
      run: |
        find mb/xmjd6/ -type f ! -name 'xmjd6.txt' -delete

    - name: Zip yong.ini and mb directory
      run: |
        zip -r yong-xmjd6.zip yong.ini mb/

    - name: Get latest release tag
      id: get_tag
      uses: actions/github-script@v7
      with:
        script: |
          const response = await github.rest.repos.getLatestRelease({
            owner: 'amorphobia',
            repo: 'rabbit',
          });
          const tagName = response.data.tag_name;
          console.log(`Latest release tag is ${tagName}`);
          return tagName;

    - name: Fetch tags and generate changelog from last release
      id: changelog
      uses: actions/github-script@v7
      with:
        script: |
          const lastRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const compare = await github.rest.repos.compareCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: lastRelease.data.tag_name,
            head: 'main'
          });
          let changelog = ''; 
          compare.data.commits.forEach(commit => {
            const message = commit.commit.message.split('\n').join(' '); 
            const commitLink = `[${commit.sha.substring(0, 7)}](https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${commit.sha})`;
            changelog += `- ${commitLink} ${message}  \n`; 
          });
          core.setOutput('changelog', changelog);

    - name: Set the tag as environment variable
      run: echo "RELEASE_TAG=${{ steps.get_tag.outputs.result }}" >> $GITHUB_ENV
    
    - name: Download the release asset
      run: |
        curl -L -o rabbit-${{ env.RELEASE_TAG }}.zip https://github.com/amorphobia/rabbit/releases/download/${{ env.RELEASE_TAG }}/rabbit-${{ env.RELEASE_TAG }}-x64.zip
      
    - name: Unzip Rabbit
      run: |
        mkdir -p Rabbit
        unzip rabbit-${{ env.RELEASE_TAG }}.zip -d Rabbit

    - name: Clean SharedSupport
      run: |
        mkdir -p /tmp/Rabbit_backup
        cp Rabbit/SharedSupport/punctuation.yaml /tmp/Rabbit_backup/
        cp Rabbit/SharedSupport/key_bindings.yaml /tmp/Rabbit_backup/
        cp Rabbit/SharedSupport/default.yaml /tmp/Rabbit_backup/
        rm -rf Rabbit/SharedSupport/*
        cp /tmp/Rabbit_backup/* Rabbit/SharedSupport/
        rm -rf /tmp/Rabbit_backup

    - name: Merge Rime into Rabbit
      run: |
        cp -r Rime/. Rabbit/SharedSupport
        zip -r Rabbit-xmjd6.zip Rabbit/
        
    - name: Create Release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.CURRENT_DATE }}
        release_name: ${{ env.RELEASE_TITLE }}
        body: |
          ## Changelog
          ${{ steps.changelog.outputs.changelog }}
          ## Release Notes
          - [如何使用](https://github.com/hugh7007/xmjd6-rere#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)
        draft: false
        prerelease: false

    - name: Upload Rabbit-xmjd6.zip to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Rabbit-xmjd6.zip
        asset_name: Rabbit-xmjd6.zip
        asset_content_type: application/zip

    - name: Upload yong-xmjd6.zip to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./yong-xmjd6.zip
        asset_name: yong-xmjd6.zip
        asset_content_type: application/zip
