name: Create Release with Zipped Branch Assets and Date

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Set up environment variables
      run: |
        echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "RELEASE_TITLE=$(date +'%Y.%m.%d') 词库更新" >> $GITHUB_ENV

    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Zip main branch files excluding .git and .github
      run: zip -r xmjd6.zip . -x "*.git*" -x "*.github*"
    
    - name: Zip main branch pure files
      run:  | 
        mkdir -p Rime
        rsync -avm --exclude='.git*' --exclude='*.github*' --exclude='squirrel*' --exclude='weasel*' --exclude='hamster*' ./Rime/

    - name: Download Rabbit-Full-x64 artifact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 设置仓库名和工作流文件名
        REPO="amorphobia/rabbit"
        WORKFLOW_FILE_NAME="ci.yml" # 你需要根据实际情况调整这个名称
          
        # 获取最新的工作流运行ID
        RUN_ID=$(curl -s \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW_FILE_NAME/runs | jq -r '.workflow_runs[0].id')
          
        # 列出该运行的artifacts
        ARTIFACTS_URL=$(curl -s \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts | jq -r '.artifacts[] | select(.name=="Rabbit-Full-x64") | .archive_download_url')
          
        # 下载artifact
        if [ ! -z "$ARTIFACTS_URL" ]; then
          curl -L \
            -o Rabbit-Full-x64.zip \
            -H "Authorization: token $GITHUB_TOKEN" \
            $ARTIFACTS_URL
        else
          echo "Artifact Rabbit-Full-x64 not found."
        fi

    - name: Unzip Rabbit-Full-x64.zip
      run: |
        unzip Rabbit-Full-x64.zip -d Rabbit-Full-x64
        
    - name: Merge Rime into Rabbit-Full-x64
      run: |
        cp -r Rime/* Rabbit-Full-x64/
        zip -r rabbit-xmjd6.zip Rabbit-Full-x64/
        
    - name: Create Release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.CURRENT_DATE }}
        release_name: ${{ env.RELEASE_TITLE }}
        body: |
          ## Release Notes
          - xmjd6: 适合新版本librime(>=1.9.0)的客户端使用。
        draft: false
        prerelease: false

    - name: Upload xmjd6.zip to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./xmjd6.zip
        asset_name: xmjd6.zip
        asset_content_type: application/zip
        
    - name: Upload Rabbit-xmjd6.zip to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rabbit-xmjd6.zip
        asset_name: Rabbit-xmjd6.zip
        asset_content_type: application/zip
