name: Create Release with Zipped Branch Assets and Date

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
    - name: Set up environment variables
      run: |
        echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "RELEASE_TITLE=$(date +'%Y.%m.%d') 词库更新" >> $GITHUB_ENV

    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Create directories
      run: |
        mkdir -p Rime
        mkdir -p mb/xmjd6  # Ensure this directory exists before writing files into it

    - name: Convert .dict.yaml files to .txt using Bash
      run: |
        for dict_file in xmjd6.zidingyi.dict.yaml xmjd6.cizu.dict.yaml xmjd6.fjcy.dict.yaml xmjd6.danzi.dict.yaml xmjd6.buchong.dict.yaml xmjd6.gbk.dict.yaml xmjd6.wxw.dict.yaml
        do
          txt_file="Rime/$(basename $dict_file .dict.yaml).txt"
          # Process file, skip lines starting with #, and swap columns if the first is not English
          awk -F'\t' '
          /^[^#]/ {
            if ($1 ~ /^[A-Za-z0-9\s]+$/) {
              print $1 "\t" $2
            } else {
              print $2 "\t" $1
            }
          }' "$dict_file" > "$txt_file"
        done

    - name: Merge all .txt files and add header
      run: |
        header='name=星猫键道6\nkey=`abcedfghijklmnopqrstuvwxyz;\\\nlen=12\nwildcard=~\nbihua=viuoa\ncode_e2=p11+p12+p21+p22+p13+p23\ncode_e3=p11+p21+p31+p13+p23+p33\ncode_a4=p11+p21+p31+n11+p13+p23+p33+n13\n[DATA]\n'
        echo -e "$header" > Rime/xmjd6.header.txt
        cat Rime/*.txt > Rime/xmjd6.body.txt
        cat Rime/xmjd6.header.txt Rime/xmjd6.body.txt > mb/xmjd6/xmjd6.txt
        rm Rime/xmjd6.header.txt Rime/xmjd6.body.txt

    - name: Remove all files except xmjd6.txt
      run: |
        find mb/xmjd6/ -type f ! -name 'xmjd6.txt' -delete

    - name: Zip yong.ini and mb directory
      run: |
        zip -r yong-xmjd6.zip yong.ini mb/

    - name: Create Rabbit-xmjd6.zip with SharedSupport
      run: |
        mkdir -p Rabbit/SharedSupport
        cp -r Rime/. Rabbit/SharedSupport
        zip -r Rabbit-xmjd6.zip Rabbit/

    - name: Get latest release tag, fetch tags, and generate changelog from last release
      id: get_tag
      uses: actions/github-script@v7
      with:
        script: |
          const response = await github.rest.repos.getLatestRelease({
            owner: 'amorphobia',
            repo: 'rabbit',
          });
          const tagName = response.data.tag_name;
          console.log(`Latest release tag is ${tagName}`);
          return tagName;

    - name: Set the tag as environment variable
      run: echo "RELEASE_TAG=${{ steps.get_tag.outputs.result }}" >> $GITHUB_ENV
    
    - name: Download the release asset
      run: |
        curl -L -o rabbit-${{ env.RELEASE_TAG }}.zip https://github.com/amorphobia/rabbit/releases/download/${{ env.RELEASE_TAG }}/rabbit-${{ env.RELEASE_TAG }}-x64.zip
      
    - name: Unzip Rabbit
      run: |
        mkdir -p Rabbit
        unzip rabbit-${{ env.RELEASE_TAG }}.zip -d Rabbit

    - name: Clean SharedSupport
      run: |
        mkdir -p /tmp/Rabbit_backup
        cp Rabbit/SharedSupport/punctuation.yaml /tmp/Rabbit_backup/
        cp Rabbit/SharedSupport/key_bindings.yaml /tmp/Rabbit_backup/
        cp Rabbit/SharedSupport/default.yaml /tmp/Rabbit_backup/
        rm -rf Rabbit/SharedSupport/*
        cp /tmp/Rabbit_backup/* Rabbit/SharedSupport/
        rm -rf /tmp/Rabbit_backup

    - name: Merge Rime into Rabbit
      run: |
        cp -r Rime/. Rabbit/SharedSupport
        zip -r Rabbit-xmjd6.zip Rabbit/
        
    - name: Create Release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.CURRENT_DATE }}
        release_name: ${{ env.RELEASE_TITLE }}
        body: |
          ## Changelog
          ${{ steps.changelog.outputs.changelog }}
          ## Release Notes
          - [如何使用](https://github.com/hugh7007/xmjd6-rere#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)
        draft: false
        prerelease: false

    - name: Upload Rabbit-xmjd6.zip to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Rabbit-xmjd6.zip
        asset_name: Rabbit-xmjd6.zip
        asset_content_type: application/zip

    - name: Upload yong-xmjd6.zip to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./yong-xmjd6.zip
        asset_name: yong-xmjd6.zip
        asset_content_type: application/zip
