name: Create Release with Zipped Branch Assets and Date

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
    - name: Set up environment variables
      run: |
        echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "RELEASE_TITLE=$(date +'%Y.%m.%d') 词库更新" >> $GITHUB_ENV

    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Zip main branch files excluding .git and .github
      run: zip -r xmjd6.zip . -x "*.git*" -x "*.github*"

    - name: Prepare Rime directory for Rabbit
      run: |
        mkdir -p Rime/
        rsync -avm --exclude='.git*' --exclude='*.github*' --exclude='squirrel*' --exclude='weasel*' --exclude='hamster*' --exclude='xmjd6.zip' . Rime/
        ls -al Rime/
        pwd

    - name: Create directories
      run: |
        mkdir -p mb/xmjd6  # Ensure the directory exists

    - name: Merge all .txt files and add header, remove extra newline after [DATA]
      run: |
        header='name=星猫键道6\nkey=`abcedfghijklmnopqrstuvwxyz;\\\nlen=12\nwildcard=~\nbihua=viuoa\ncode_e2=p11+p12+p21+p22+p13+p23\ncode_e3=p11+p21+p31+p13+p23+p33\ncode_a4=p11+p21+p31+n11+p13+p23+p33\n[DATA]'
        echo -e "$header" > Rime/xmjd6.header.txt
        cat Rime/*.txt > Rime/xmjd6.body.txt
        echo -n "$(cat Rime/xmjd6.header.txt Rime/xmjd6.body.txt)" > mb/xmjd6/xmjd6.txt
        rm Rime/xmjd6.header.txt Rime/xmjd6.body.txt

    - name: Zip xmjd6.txt file
      run: |
        if [ -f mb/xmjd6/xmjd6.txt ]; then
          zip -j mb/xmjd6.zip mb/xmjd6/xmjd6.txt
          echo "xmjd6.txt has been successfully zipped."
        else
          echo "Error: xmjd6.txt does not exist in the mb/xmjd6 directory."
          exit 1
        fi

    - name: Zip yong.ini and mb directory
      run: |
        echo "Dummy content for yong.ini" > yong.ini  # Creating a dummy yong.ini file for example
        zip -r yong-xmjd6.zip yong.ini mb/

    - name: Create Rabbit-xmjd6.zip with SharedSupport
      run: |
        mkdir -p Rabbit/SharedSupport
        cp -r Rime/. Rabbit/SharedSupport
        zip -r Rabbit-xmjd6.zip Rabbit/

    - name: Create Release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.CURRENT_DATE }}
        release_name: ${{ env.RELEASE_TITLE }}
        body: |
          ## Changelog
          ## Release Notes
          - [如何使用](https://github.com/hugh7007/xmjd6-rere#如何使用)
        draft: false
        prerelease: false

    - name: Upload all zipped files to Release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Rabbit-xmjd6.zip
        asset_name: Rabbit-xmjd6.zip
        asset_content_type: application/zip
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./yong-xmjd6.zip
        asset_name: yong-xmjd6.zip
        asset_content_type: application/zip
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./xmjd6.zip
        asset_name: xmjd6.zip
        asset_content_type: application/zip
