name: Package Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/upload-artifact@v3
      with:
        name: xmjd6
        path: |
          **/*
          !.git/**
          !.github/
