name: Package Legacy Branch

on:
  push:
    branches:
      - legacy
  pull_request:
    branches:
      - legacy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/upload-artifact@v3
      with:
        name: xmjd6-legacy
        path: |
          **/*
          !.git/**
          !.github/
